# Generated by Django 5.2.10 on 2026-01-13 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Itineraries',
                'db_table': 'itinerary',
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('commission_client_wise', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='agency.agency')),
            ],
            options={
                'db_table': 'agent',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField()),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='agent.agent')),
            ],
            options={
                'db_table': 'activity_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('dob', models.DateField(blank=True, null=True)),
                ('client_type', models.CharField(choices=[('SINGLE', 'Single'), ('COUPLE', 'Couple'), ('FAMILY_FRIENDS', 'Family/Friends'), ('CORPORATE', 'Corporate')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('travel_date', models.DateField(blank=True, null=True)),
                ('destination', models.CharField(blank=True, max_length=255, null=True)),
                ('origin', models.CharField(blank=True, max_length=255, null=True)),
                ('budget_range', models.CharField(blank=True, max_length=100, null=True)),
                ('travel_style', models.CharField(blank=True, choices=[('LUXURY', 'Luxury'), ('BUDGET', 'Budget'), ('ADVENTURE', 'Adventure'), ('BUSINESS', 'Business'), ('FAMILY', 'Family')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='agent.agent')),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='ClientFamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('relation', models.CharField(choices=[('SPOUSE', 'Spouse'), ('CHILD', 'Child'), ('FRIEND', 'Friend'), ('RELATIVE', 'Relative'), ('COLLEAGUE', 'Colleague')], max_length=20)),
                ('age_group', models.CharField(choices=[('ADULT', 'Adult'), ('CHILD', 'Child')], max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='agent.client')),
            ],
            options={
                'db_table': 'client_family_member',
            },
        ),
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='agent.itinerary')),
            ],
            options={
                'db_table': 'itinerary_day',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('itineraryactivity_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('itinerary_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='agent.itineraryday')),
            ],
            options={
                'verbose_name_plural': 'Itinerary Activities',
                'db_table': 'itinerary_activity',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(default=1)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('ai_base_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='agent.agent')),
            ],
            options={
                'db_table': 'quote',
            },
        ),
        migrations.AddField(
            model_name='itinerary',
            name='quote',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='agent.quote'),
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hotel_currency', models.CharField(default='USD', max_length=3)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('review_count', models.IntegerField(blank=True, null=True)),
                ('star_rating', models.IntegerField(blank=True, null=True)),
                ('country_code', models.CharField(blank=True, max_length=2, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('main_photo_url', models.URLField(blank=True, null=True)),
                ('checkin_time', models.TimeField(blank=True, null=True)),
                ('checkout_time', models.TimeField(blank=True, null=True)),
                ('room_type', models.JSONField(blank=True, default=list)),
                ('labels', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(default='Booking.com', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='agent.quote')),
            ],
            options={
                'db_table': 'hotel',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_type', models.CharField(choices=[('OUTBOUND', 'Outbound'), ('RETURN', 'Return')], max_length=10)),
                ('travel_class', models.CharField(choices=[('ECONOMY', 'Economy'), ('BUSINESS', 'Business'), ('FIRST', 'First')], max_length=10)),
                ('price_per_seat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carrier', models.CharField(blank=True, max_length=100, null=True)),
                ('flight_currency', models.CharField(default='USD', max_length=3)),
                ('source', models.CharField(default='Duffel', max_length=50)),
                ('departure_datetime', models.DateTimeField(blank=True, null=True)),
                ('departure_airport', models.CharField(blank=True, max_length=10, null=True)),
                ('arrival_datetime', models.DateTimeField(blank=True, null=True)),
                ('arrival_airport', models.CharField(blank=True, max_length=10, null=True)),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('stops', models.IntegerField(default=0)),
                ('baggage_include', models.CharField(blank=True, max_length=255, null=True)),
                ('flight_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='agent.quote')),
            ],
            options={
                'db_table': 'flight',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('to_airport', models.CharField(blank=True, max_length=10, null=True)),
                ('from_airport', models.CharField(blank=True, max_length=10, null=True)),
                ('is_booked', models.BooleanField(default=False)),
                ('destination_city', models.CharField(blank=True, max_length=255, null=True)),
                ('destination_country', models.CharField(blank=True, max_length=255, null=True)),
                ('destination_formatted', models.TextField(blank=True, null=True)),
                ('destination_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('destination_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='agent.agent')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='agent.client')),
            ],
            options={
                'db_table': 'trip',
            },
        ),
        migrations.AddField(
            model_name='quote',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='agent.trip'),
        ),
        migrations.AlterUniqueTogether(
            name='quote',
            unique_together={('trip', 'version_number')},
        ),
    ]
