# Generated by Django 5.1.7 on 2026-01-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='table_name',
            field=models.CharField(blank=True, choices=[('AGENT', 'Agent'), ('AGENCY', 'Agency'), ('CLIENT', 'Client'), ('TRIP', 'Trip'), ('QUOTE', 'Quote'), ('FLIGHT', 'Flight'), ('HOTEL', 'Hotel'), ('ITINERARY', 'Itinerary'), ('USER', 'User'), ('SUPPLIER', 'Supplier')], max_length=20, null=True),
        ),
    ]
