# Generated by Django 5.1.7 on 2026-01-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_agent_user_quote_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('INITIAL_CONTACT', 'Initial Contact'), ('QUOTE_SENT', 'Quote Sent'), ('IN_NEGOTIATION', 'In Negotiation'), ('CONFIRMED', 'Confirmed'), ('REMOVED', 'Removed')], default='DRAFT', max_length=30),
        ),
    ]
