# Generated by Django 5.1.7 on 2026-01-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_alter_quote_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='destination_country_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='geocoding_confidence',
            field=models.FloatField(default=0.0),
        ),
    ]
