# Generated by Django 5.1.7 on 2026-01-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_trip_destination_country_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
