# Generated by Django 5.1.7 on 2026-01-17 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_alter_supplier_type'),
        ('agent', '0006_client_notes_alter_agent_email_alter_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='agency.agency'),
        ),
    ]
