# Generated by Django 5.1.7 on 2026-01-18 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0008_client_commission_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='agent.client'),
        ),
    ]
