# Generated by Django 5.1.7 on 2026-01-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0009_activitylog_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='membership',
            field=models.CharField(blank=True, choices=[('GOLD', 'Gold'), ('SILVER', 'Silver'), ('PLATINUM', 'Platinum')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='carrier_logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
