# Generated by Django 5.1.7 on 2026-01-21 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0010_client_membership_flight_carrier_logo'),
        ('chatbot', '0003_remove_aichatsession_related_quote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='ai_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='chatbot.aichatsession'),
        ),
    ]
