# Generated by Django 5.1.7 on 2026-01-20 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_drop_tasks_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aichatsession',
            name='related_quote',
        ),
        migrations.RemoveField(
            model_name='aichatsession',
            name='related_trip',
        ),
    ]
