# Generated by Django 5.2.10 on 2026-01-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_alter_supplier_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='type',
            field=models.CharField(choices=[('DUFFEL', 'Duffel'), ('AMADEUS', 'Amadeus'), ('BOOKING.COM', 'Booking.com')], max_length=20),
        ),
    ]
