# Generated by Django 5.1.7 on 2026-01-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_alter_supplier_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='category',
            field=models.CharField(choices=[('FLIGHT', 'Flight'), ('HOTEL', 'Hotel'), ('BOTH', 'Both')], default='BOTH', max_length=10),
        ),
        migrations.AddField(
            model_name='supplier',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
